### ISSUE TITLE
keys(), values(), items() fails when query is exactly in the trie

### ISSUE THREAD

**Issue by zpincus** [fnl/patricia-trie#1]
The following produces an IndexError in `trie._find()`:

```
t = trie(foo=5)
list(t.keys('foo'))
```

To fix this, `trie._scan()` needs to read as follows:

```
    def _scan(self, rvalFun, string, start=0, *end):
        node = self
        if start < 0:
            start = max(0, len(string) + start)
        while node is not None:
            if node._value is not __NON_TERMINAL__:
                yield rvalFun(string, start, node._value)
            if start >= len(string):
                break
            node, start = node._find(string, start, *end)
```

That is, the `if start >= len(string): break` part is necessary to not keep looking for prefixes past the full length of the query string.

**Comment by fnl** [comment]
Hi @zachrahan!

First, thanks for using patricia-trie - hope you can make good use of it!
I've added your example case as a test case (28efa98ad37eafd85a4e5d9008e954ffe022a6e6), which reproduces the problem you describe.
Note that the final fix I made is in `trie._find()`, to make sure the index error does not occur from elsewhere, either (see 4b26dff8bfe84e8d6a1a5c353b9524eb5a9fee3a).
Thanks to your report I also took the time to fix a few code-smell issues and a failing test case that was ill-defined.
Happy coding!

hand;fnl

**Comment by zpincus** [comment]
That's a much better fix than my suggestion! Thanks. And thanks for the code: it's nice to have a simple pure-python trie for when one doesn't need to have something more heavy-weight with a C implementation etc.
